name = "10-minute-timer"
workers_dev = true
main = "workers-site/index.js"
compatibility_date = "2025-08-18"
account_id = "5c22bca118f3aff455dce4c65d36e343"

[site]
bucket = "./"

# 自定义域名配置
# 如果您的域名已添加到Cloudflare，取消注释下面的配置
routes = [
  { pattern = "10-minute-timer.website/*", zone_name = "10-minute-timer.website" },
  { pattern = "www.10-minute-timer.website/*", zone_name = "10-minute-timer.website" }
]

[[kv_namespaces]]
binding = "STATE_KV"
# KV命名空间ID已更新
id = "7506bd4db8f64e4a9f9e98918cf570c1"

# 环境变量配置
[vars]
ADMIN_TOKEN = "Cjh110110" 