# Cloudflare Worker 配置
name = "10-minute-timer"
main = "_worker.js"
compatibility_date = "2024-09-11"

# Durable Objects 配置 - 用于WebSocket会话管理
[[durable_objects.bindings]]
name = "TIMER_SESSIONS"
class_name = "TimerSession"

# 环境变量
[vars]
NODE_ENV = "production"

# Durable Objects 迁移
[[migrations]]
tag = "v1"
new_sqlite_classes = ["TimerSession"] 